import Head from 'next/head'
import Info from '../../components/Info'

export default function Home({page, params}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Info />
    </div>
  )
}