import Head from 'next/head'
import Main from '../../components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="WebBadminton Items" />
        <meta property="og:url" content="http://localhost:3000/doctors" />
        <meta property="og:type" content="article" />
      </Head>
      <Main />
    </div>
  )
}
